server:
  port: 8085

spring:
  main:
   web-application-type: reactive
  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # Apply CORS settings to all paths
            allowedOrigins:
              - "http://localhost:3000" # Your frontend's origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # Allow all headers
            allowCredentials: true # Allow cookies if required
      routes:        
        - id: user-service
          uri: http://usermanagement:8091
          predicates:
            - Path=/api/auth/**
        - id: order-service
          uri: http://localhost:8092
          predicates:
            - Path=/orders/**
        - id: article-service
          uri: http://articlediscover:8090
          predicates:
            - Path=/articles/**
            
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    