server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://localhost:8092
          predicates:
            - Path=/orders/**
        - id: article-service
          uri: http://localhost:8090
          predicates:
            - Path=/articles/**
