name : Build & Deploy solide_api_gateway app

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    name:  Build & Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          
#      - name: Unit Tests
#        run: mvn -B test --file pom.xml
         
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-     
         
      - name: Build with Maven
        run: |
          mvn clean compile
          mvn -B package --file pom.xml 
          
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/solide_api_gateway:latest
           
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/solide_api_gateway:latest
               
           
           
           